# Thanks to https://medium.com/neudesic-innovation/building-multi-platform-container-images-with-github-actions-e495f9441ad3

name: Create and push image to ghcr.io upon release creation

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - architecture: amd64
            os: ubuntu-24.04
          - architecture: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v4
      - name: Log into container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Write fully qualified image name to use
        run: |
          IMAGE_NAME_FULL_RAW="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          printf "IMAGE_NAME_FULL=%s\n" "${IMAGE_NAME_FULL_RAW,,}" >> $GITHUB_ENV
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          # We want to avoid polluting the registry with too many arch-specific tags
          # We also want to be able to have descriptions
          outputs: type=registry,name=${{ env.IMAGE_NAME_FULL }},push-by-digest=true,oci-mediatypes=true
          platforms: linux/${{ matrix.architecture }}
          build-args: |
            GIT_VERSION_TAG=${{ github.event.release.tag_name }}
            GIT_VERSION_HASH=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # We want BuildKit attestation
          provenance: true
          sbom: true
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.push.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-linux-${{ matrix.architecture }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1
  merge:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Get Docker Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.release.tag_name }}
            type=semver,pattern=v{{version}},value=${{ github.event.release.tag_name }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ github.event.release.tag_name }}
            type=semver,pattern=v{{major}},value=${{ github.event.release.tag_name }}
          # Assumption is that we only publish tags for latest major, minor releases
          flavor: |
            latest=${{ !github.event.release.prerelease }}
      - name: Create manifest list and push
        id: push
        working-directory: ${{ runner.temp }}/digests
        run: |
          IMAGE_NAME_LOWER=${IMAGE_NAME,,}

          # Using jq to avoid issues with empty lines and multi-line items

          read -r -a TAG_ARGS <<< "$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")"

          # Doing it this way to be very careful with space breaks
          ANNOTATION_ARGS=()
          while IFS= read -r annotation; do
            [[ -n "$annotation" ]] && ANNOTATION_ARGS+=(--annotation "index:${annotation}")
          done < <(jq -cr '.labels | to_entries | map(.key + "=" + .value)[]' <<< "$DOCKER_METADATA_OUTPUT_JSON")

          DIGEST_TARGETS=()
          for file in *; do
            [[ -f "$file" ]] && DIGEST_TARGETS+=("${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}@sha256:${file}")
          done

          docker buildx imagetools create \
            "${TAG_ARGS[@]}" \
            "${ANNOTATION_ARGS[@]}" \
            "${DIGEST_TARGETS[@]}"
          
          digest=$(docker buildx imagetools inspect \
            ${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:${{ steps.meta.outputs.version }} \
            --format '{{json .Manifest.Digest}}' | sed 's/^"//;s/"$//' )
          printf "digest=%s\n" "$digest" >> $GITHUB_OUTPUT
          printf "Digest is: %s\n" "$digest"
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
